### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by zelohon** [std66/TomiSoft.YoutubeDownloader.WebUI#7]
![1](https://user-images.githubusercontent.com/36800197/106010927-f134fb00-60f4-11eb-9227-948f97245aba.png)

What's wrong?

**Comment by std66** [comment]
You can find the application logs in [application_dir]\logs folder (the ones called 'nlog-own-*.log'). Could you please provide it to me, so that I can take a look at it?

**Comment by std66** [comment]
As an alternative option, today I've created a Docker image which is preconfigured and contains everything it needs to run properly. You can find it here:
https://hub.docker.com/r/std66/tomisoft-youtubedownloader-webui

**Comment by zelohon** [comment]
> 您可以在 [application_dir] 日志文件夹中找到应用程序日志（称为"nlog-own-.log"）。你能把它给我，以便我看看吗？

[nlog-own-2021-01-27.log](https://github.com/std66/TomiSoft.YoutubeDownloader.WebUI/files/5886453/nlog-own-2021-01-27.log)
Seems to be unable to find the plug-in, but I do not know where the plug-in download!

**Comment by std66** [comment]
Please check if you have the following applications present on your machine in the same directory:
- ffmpeg.exe
- youtube-dl.exe
On Windows, if you are using IIS, you need to give IUSR read+execute permissions for these applications.

You also need to provide the absolute path of youtube-dl.exe in appsettings.json. For example, if you have youtube-dl.exe and ffmpeg.exe in C:\youtube-dl folder, the appsettings.json should have this parameter with this value:
```
"ExecutablePath": "C:\\youtube-dl\\youtube-dl.exe"
```

**Comment by std66** [comment]
You can download ffmpeg.exe from https://ffmpeg.org/ and youtube-dl.exe from https://youtube-dl.org/downloads/latest/youtube-dl.exe

**Comment by zelohon** [comment]
Well, thank you!

I just tested the docker single video download OK, list form of all videos can not be downloaded!

I want to make two suggestions!

1. It would be great if docker could add the video list download function (download all videos)!

2. Docker wants to add the function of specified download directory!

3. It is recommended to have an optional definition option when downloading the video!

4. When downloading the video, it is recommended to have an option to download the cover map!

**Comment by std66** [comment]
I'm happy to hear that the Docker image works for you :)

Thank you for the feedback. Downloading playlists and splitting a video by timestamps are features I also want to implement, so it is definitely on the roadmap. I'm not sure when I will have time to get it done, however. At the beginning, I designed this website to download a single video. As for the video quality (definition), it downloads the content in the best possible quality available. After downloading, you can use already existing tools to transcode the video/audio.

**Comment by zelohon** [comment]
> I'm happy to hear that the Docker image works for you :)
> 
> Thank you for the feedback. Downloading playlists and splitting a video by timestamps are features I also want to implement, so it is definitely on the roadmap. I'm not sure when I will have time to get it done, however. At the beginning, I designed this website to download a single video. As for the video quality (definition), it downloads the content in the best possible quality available. After downloading, you can use already existing tools to transcode the video/audio.


OK, thank you very much! I love your project!
